ALTER TABLE events ADD COLUMN IF NOT EXISTS scroll_depth_pct NUMERIC;
ALTER TABLE events ADD COLUMN IF NOT EXISTS page_height INTEGER;

CREATE TABLE IF NOT EXISTS sus_responses (
  id           SERIAL PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id      INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  q1  SMALLINT NOT NULL CHECK (q1  BETWEEN 1 AND 5),
  q2  SMALLINT NOT NULL CHECK (q2  BETWEEN 1 AND 5),
  q3  SMALLINT NOT NULL CHECK (q3  BETWEEN 1 AND 5),
  q4  SMALLINT NOT NULL CHECK (q4  BETWEEN 1 AND 5),
  q5  SMALLINT NOT NULL CHECK (q5  BETWEEN 1 AND 5),
  q6  SMALLINT NOT NULL CHECK (q6  BETWEEN 1 AND 5),
  q7  SMALLINT NOT NULL CHECK (q7  BETWEEN 1 AND 5),
  q8  SMALLINT NOT NULL CHECK (q8  BETWEEN 1 AND 5),
  q9  SMALLINT NOT NULL CHECK (q9  BETWEEN 1 AND 5),
  q10 SMALLINT NOT NULL CHECK (q10 BETWEEN 1 AND 5),
  sus_score    NUMERIC(5,2) NOT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT NOW()
);